
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloServiceImpService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8083/service/hello?wsdl")
public class HelloServiceImpService
    extends Service
{

    private final static URL HELLOSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVICEIMPSERVICE_EXCEPTION;
    private final static QName HELLOSERVICEIMPSERVICE_QNAME = new QName("http://service/", "HelloServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/service/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERVICEIMPSERVICE_WSDL_LOCATION = url;
        HELLOSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public HelloServiceImpService() {
        super(__getWsdlLocation(), HELLOSERVICEIMPSERVICE_QNAME);
    }

    public HelloServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVICEIMPSERVICE_QNAME, features);
    }

    public HelloServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVICEIMPSERVICE_QNAME);
    }

    public HelloServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVICEIMPSERVICE_QNAME, features);
    }

    public HelloServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloServiceImp
     */
    @WebEndpoint(name = "HelloServiceImpPort")
    public HelloServiceImp getHelloServiceImpPort() {
        return super.getPort(new QName("http://service/", "HelloServiceImpPort"), HelloServiceImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServiceImp
     */
    @WebEndpoint(name = "HelloServiceImpPort")
    public HelloServiceImp getHelloServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "HelloServiceImpPort"), HelloServiceImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw HELLOSERVICEIMPSERVICE_EXCEPTION;
        }
        return HELLOSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
